### ISSUE TITLE
Learn to make Readme

### ISSUE THREAD

**Issue by maektwain** [upscaletech/finocial.ui#1]
A great project starts with good documentation, if however you are building it yourself then its fine, but if you work with teams then I would suggest create a readable Readme.

A typical readme consist of following

1. Define what is the project about 
2. Share how to run it.
3. What is purpose if any
4. Define todo
5. Allow and help others to understand a specific part of app which you don't want to do.
6. Set guidelines and standard
7.  Last but not least @Author Name also 

Thanks

**Comment by Devilla** [comment]
Done.
