### ISSUE TITLE
Bug While Creating a Transaction

### ISSUE THREAD

**Issue by maektwain** [upscaletech/finocial.ui#16]
When you create a loan request there are few issues, APR seems to be showing NAN

Plus when creating a transaction it asks for the Metamask request and then fails with the below screenshot.

Follow the steps to reproduce 

1. lock metamask / Open Browser without unlocking metamask
2. Create loan request 
3. Open's Up metamask , approve lending.
4. Then boom

<img width="1236" alt="Screenshot 2019-09-10 at 5 37 08 PM" src="https://user-images.githubusercontent.com/8274610/64623675-0b801300-d3f2-11e9-95ed-549dd393da4d.png">

**Comment by Devilla** [comment]
![Screenshot from 2019-09-10 20-18-26](https://user-images.githubusercontent.com/15603274/64624581-8522fb80-d408-11e9-994c-7593fdd9f0f3.png)
![Screenshot from 2019-09-10 20-18-31](https://user-images.githubusercontent.com/15603274/64624593-87855580-d408-11e9-9f57-11dd84bafcd8.png)

It's working I just checked. Check why it's failing for you.

**Comment by Devilla** [comment]
If occurs again reopen the issue.
