### ISSUE TITLE
View all Requests UI

### ISSUE THREAD

**Issue by Devilla** [upscaletech/finocial.ui#18]
The values are not updated for Loan Data.
![Screenshot from 2019-09-11 13-28-10](https://user-images.githubusercontent.com/15603274/64678898-27d68b00-d498-11e9-8a4a-bd5efda9219f.png)

**Comment by maektwain** [comment]
Could you specify it a bit? what value you are talking about and how do we reproduce it?

**Comment by Devilla** [comment]
![image](https://user-images.githubusercontent.com/15603274/64750358-4b501300-d536-11e9-98da-08d7c591c278.png)
![image](https://user-images.githubusercontent.com/15603274/64750400-6d499580-d536-11e9-94fe-6ee7939aaf8e.png)

Logs for LoanData and Loan Amount.

**Comment by livingrock7** [comment]
probably just mumbo jumbo with old ABIs and naming convention.  Make it smooth or else we will suffer in debugging. 

Also loan attributes are new and their order

**Comment by Devilla** [comment]
Yeah indexing was the issue, new contract have different indexing than previous one!
