### ISSUE TITLE
Loan request UI breakdown creating a loan request.

### ISSUE THREAD

**Issue by Devilla** [upscaletech/finocial.ui#2]
Probable causes :

1. Metamask not logged in.

2. Privacy mode is enable in metamask by default.

url : https://blocklender.herokuapp.com/request

**Comment by livingrock7** [comment]
Fixed metamask breaking change by asking user's permissions using ethereum.enable()

**Comment by Devilla** [comment]
Done and deployed! Happy Hacking :1st_place_medal:

**Comment by livingrock7** [comment]
Bug was observed in case user is not logged in already

**Comment by livingrock7** [comment]
still breaking down if not logged in metamask

**Comment by Devilla** [comment]
![Screenshot from 2019-09-18 19-44-13](https://user-images.githubusercontent.com/15603274/65156454-c3459e00-da4c-11e9-919b-4c11b300c631.png)
![Screenshot from 2019-09-18 19-44-02](https://user-images.githubusercontent.com/15603274/65156455-c3de3480-da4c-11e9-878c-216a6f032ac5.png)
![Screenshot from 2019-09-18 19-43-53](https://user-images.githubusercontent.com/15603274/65156456-c3de3480-da4c-11e9-9512-19da99401c9d.png)

Working here perfectly why it's failing for you can you show.

**Comment by livingrock7** [comment]
i observed it failing once. other alerts and notifications are not as intended look into those!

**Comment by Devilla** [comment]
Show me also na then only I can figure out the issue if there exists any and provide solution for it.

**Comment by livingrock7** [comment]
I will update here can't find screenshot and reproduce. Don't pick this
simplest for now other important issues you have closed before any testing.
Do look into those other reopened
