### ISSUE TITLE
Loan Request UI Notification after loancontract is created

### ISSUE THREAD

**Issue by livingrock7** [upscaletech/finocial.ui#5]
afterOnClick()

flow: create - transfer in metamask -> txn created -> mined (check from receipt)-> get contract address (check from event log args)

once contract address is obtained, display message
" Congratulations! Loan Request is Created successfully!"
You can check the contract on ethereum here:
https://ropsten.etherscan.io/address/<contract address>

**Comment by Devilla** [comment]
Done.

**Comment by livingrock7** [comment]
URL on the button is wrong like it is appended after heroku url. 

also the contract address is not right. it should be the contract address from the receipt logs and not from the receipt's field contract address.

**Comment by Devilla** [comment]
Okay, I checked let me fix it.
